### ISSUE TITLE
The v0.1.2 file is empty.

### ISSUE THREAD

**Issue by Miraakz9** [nopeless/doki-theme-musicbee#1] opened 2023-02-13 23:14 UTC
It's just a 425 Bytes empty file and contains no skins.

**Comment by nopeless** [comment] 2023-02-14 02:09
crap; ill look into it

**Comment by nopeless** [comment] 2023-02-14 03:17
@Miraakz9 Thanks for the issue. The problem is fixed now. Have a good day

**Closed as completed** 2023-02-14 03:17 UTC
